name: Deploy Feature Branch

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop
    paths:
      - 'src/**'
      - 'test/**'
      - '**.cake'
      - '.github/workflows/branch-feature.yml'
      - '.github/workflows/step-*.yml'
  workflow_dispatch:

jobs:
  get-version:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/step-version.yml
    secrets: inherit
    with:
      is-pre-release: true
      version-suffix: ${{ github.head_ref }}

  build:
    needs: [get-version]
    uses: ./.github/workflows/step-build.yml
    secrets: inherit
    with:
      version: ${{ needs.get-version.outputs.version }}
      checkout-ref: ${{ github.head_ref }}
      
  check-markdown:
    needs: [get-version]
    uses: ./.github/workflows/step-check-markdown.yml
    secrets: inherit

  publish-to-nuget:
    needs: [get-version,build]
    uses: ./.github/workflows/step-publish.yml
    secrets: inherit
    with:
      deploy-env: github-beta
      deploy-branch: ${{ github.base_ref }}
      version: ${{ needs.get-version.outputs.version }}
  
  tag-release:
    needs: [get-version,publish-to-nuget]
    uses: ./.github/workflows/step-tag-release.yml
    with:
      version: ${{ needs.get-version.outputs.version }}