name: Check PR

on:
  pull_request_target:
    types: [opened, synchronize]
    branches:
      - develop
    paths:
      - 'src/**'
      - 'test/**'
      - '**.cake'
      - '.github/workflows/pr.yml'
      - '.github/workflows/step-*.yml'
  workflow_dispatch:

jobs:
  get-version:
    if: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
    uses: ./.github/workflows/step-version.yml
    secrets: inherit
    with:
      version-suffix: ${{ github.head_ref }}

  build:
    needs: [get-version]
    uses: ./.github/workflows/step-build.yml
    secrets: inherit
    with:
      version: ${{ needs.get-version.outputs.version }}
      checkout-ref: ${{ github.head_ref }}
      
  check-markdown:
    needs: [get-version]
    uses: ./.github/workflows/step-check-markdown.yml
    secrets: inherit