on:
  workflow_call:
    inputs:
      deploy-env:
        required: true
        description: 'Environment to deploy to'
        type: string
      deploy-branch:
        required: true
        description: 'Branch to deploy'
        type: string
      version:
        description: 'The version number to use for the build'
        required: true
        type: string
      package-name:
        description: 'The name of the package to push'
        required: true
        type: string
  
jobs:
  push-package:
    runs-on: ubuntu-latest
    environment: ${{ inputs.deploy-env }}
    steps:
      - name: Download Package
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.package-name }}
          path: ./src/Xunit.OpenCategories/bin/Release
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 8.0.x
      - name: Publish Package
        if: ${{ inputs.deploy-env == 'github-beta' }}
        run: |
          dotnet nuget add source --username baynezy --password ${{ secrets.NUGET_API_KEY }} --store-password-in-clear-text --name github ${{ vars.NUGET_SOURCE }}
      - name: Push package to NuGet
        run: |
          dotnet nuget push $(find ./src/Xunit.OpenCategories/bin/Release/*.nupkg) --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ vars.NUGET_SOURCE }}